primary_color = "#007BFF"
secondary_color = "#FFC107"
background_color = "#F8F9FA"
text_color = "#212529"
data_folder = 'data'
header_style = {"textAlign": "center", "color": text_color}
subheader_style = {"textAlign": "left", "color": text_color, "padding": "5px 0px"}
playoff_right = 2000
playoff_top = 1000
field_length = 105
field_width = 68